version: '3.9'
services:
  mysql:
    image: mysql:8.0.32
    ports:
      - 3306:3306
    volumes:
      - ./seed:/docker-entrypoint-initdb.d
      - ./mysql_data:/var/lib/mysql

    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  webserver:
    image: php-webserver
    build: 
      context: ./
    ports:
        - 80:80
    volumes:
        - ./html:/var/www/html
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}